### ISSUE TITLE
Boolean return values are too verbose

### ISSUE THREAD

**Issue by shepmaster** [laboon/ebook#111]
This is my code-review side kicking in, but you should never write:

```java
if (a == b) {
  return true;
} else {
  return false;
}
```

Instead, you just write

```java
return a == b;
```

I'm more than happy to make these changes (and there are multiple), but I wanted to see if there was a reason to you were using this style.

**Comment by timparenti** [comment]
More verbose, yes, but from a pedagogical standpoint, I could argue it's more clear as-is.  It's not inherently obvious to the novice what's going on when you return a Boolean in the fashion you suggest, and explaining that is not really the point of this text.

**Comment by laboon** [comment]
@shepmaster You're not the first to argue this, but since this is a book for novices - some of testing students are basically straight out of Data Structures - I want to go with the most explicit rendition I can.  It's not something I would put into a project myself, but for pedagogical reasons I'm keeping it here.

In other words, "what @timparenti said." =)
