### ISSUE TITLE
Potential capitalization Issue

### ISSUE THREAD

**Issue by r7y** [laboon/ebook#140]
The chapter on performance testing says, "Imagine a video game where you play a software tester fighting evil Bugs." I'm not sure if this was intended, but "Bugs" was capitalized even though it does not seem to be a proper noun.

**Comment by timparenti** [comment]
I think this is perhaps just a bit of good-natured absurdism, but since it is in fact the only place this appears (and the word "bug" is avoided in most other contexts), it does seem a bit off.

Personally, to retain the absurdist element of the proposed video game, my solution would be to also capitalize "Evil", as in "Evil Bugs".

**Comment by laboon** [comment]
Exactly my intent, although @timparenti said it more eloquently than I would have.  Fixed in commit 7837367 by capitalizing 'evil' as well.
