### ISSUE TITLE
Cite sources for code review and pair programming claims?

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#27]
I actually don't know of any empirical research that shows these improve software quality :-/ I wouldn't be surprised if these are the equivalent of the best alchemy practices we know of at the moment...

**Comment by laboon** [comment]
Pretty sure there is some in Code Complete 2.  I'll check and either add a reference or delete / reword.

In fact, this book could probably use some more reference adding in general.

**Comment by laboon** [comment]
"there is some"?  I swear I have lost the ability to communicate cogently.

Page 470 and 472 of Code Complete have charts showing the efficacy of different defect detection techniques, with references to the studies where they were found.  I have just added a simple reference to this section, but let me know if you think I should go into more detail.  Since it's not really the topic of the book - just a note that "testing isn't the only way to improve quality" - I didn't want to go too much down the rabbit hole.

**Comment by laboon** [comment]
Address in aff4b48
