### ISSUE TITLE
Single fancy quote is going the wrong way, once

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#33]
In the rendered PDF version built 2015-08-21, in section 6.1.5, *one* of the single smart/fancy/pretty whatever quotes, the first one around the first `a`, is going the wrong way as shown in the screenshot; the incorrect one is highlighted in red and other quotes that are displayed as I would expect are highlighted in green.

<img width="809" alt="screen shot 2015-08-17 at 2 00 45 pm" src="https://cloud.githubusercontent.com/assets/193874/9424893/5bf1af1c-48cb-11e5-8b3f-53a289de046d.png">

All of these characters appear to be ASCII 39 in the markdown... sooooo.... something in the md -> pdf toolchain must be doing it...

**Comment by timparenti** [comment]
I'll take a look into this one, and perhaps file a bug on the offending project, if necessary.

**Comment by laboon** [comment]
That's weird.  No matter what I changed, that fancy quote kept getting messed up.

As a workaround, I've changed the chars to strings by using double-quotes in commit de15a62.  The particular data type is irrelevant in this example. That doesn't resolve the underlying issue, of course.  @timparenti I'm happy to keep this issue open if you like if you want to use it to keep track of it, or just close it, whichever you prefer.

**Comment by timparenti** [comment]
If you don't mind, @laboon, let's leave this open just for now.

Since these should probably really be inline verbatims, I'd thought, e.g.,
```markdown
'`a`', '`b`', '`c`'
```
might help.  However, I was surprised to find that, in that case, __all__ of the single-quotes became incorrect except for the one _after_ the _last_ 'a':

![2015-08-22_laboon-ebook-issue33](https://cloud.githubusercontent.com/assets/236283/9425434/835effd8-48de-11e5-97eb-14c04f724a5a.png)

My guess is that something is not quite right in `pandoc`'s heuristics for smart quotes.  Specifically, although you generally want "open"-quotes after whitespace, there are known cases in which you actually want an apostrophe ("close" single quote) instead, e.g., ’90s instead of ‘90s.  The generated TeX confirms `pandoc` is involved somehow:

```latex
Depending on whether
\lstinline!SORT_ASCENDING! (a boolean flag) is set to true or false, it
will either sort ascending (from the lowest value to the highest - e.g.,
'a', `b', `c') or sort descending (from the highest value to the lowest
- e.g., `c', `b', `a'). 
```

Clearly the presence of `e.g.,` before this isn't causing it, or we'd see the same behavior in the other list.  But I have no idea what `a` has to do with it.

**Comment by timparenti** [comment]
I found a thing. It apparently has to do with the verbatims:

![2015-08-24_laboon-ebook-issue33-2](https://cloud.githubusercontent.com/assets/236283/9451338/08c85824-4a7c-11e5-8518-72b22dbad000.png)

That also explains why adding more verbatims to the paragraph reversed all of the quotes.  Whatever algorithm is matching the single-quote characters to each other is failing here.

**Comment by timparenti** [comment]
It appears this is the result of faulty tokenization of the `'s` suffix (presumably as a separate word) after forms of emphasis such as bold, italic, strikethrough, and teletype/verbatim.

This was reported to `pandoc` on 12 June 2015 as jgm/pandoc#2228.

**Comment by carols10cents** [comment]
SO CLOSED.
