### ISSUE TITLE
Ambiguous sentence - not sure how to reword

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#37]
In section 7.1:

> If nothing is preventing odd input coming in, at some point it probably will.

My sleepy brain resolved this sentence to mean "If nothing is preventing odd input coming in, at some point the system probably will prevent odd input coming in" rather than the intended "If nothing is preventing odd input coming in, at some point odd input probably will come in".

My sleepy brain is unable to come up with a sufficiently pithy yet unambiguous way to reword this, though... "If nothing is preventing odd input coming in, at some point War and Peace probably will come in as a product name", "If nothing is preventing odd input coming in, at some point it will probably be like living under a leaky roof"...? 

Meh. You're the writer here, so I'm leaving this one to you rather than submitting a correction :)

**Comment by laboon** [comment]
I ended up re-wording that entire paragraph, because it did not flow very well.

"    In order to check for logic errors, you should ensure that the expected result occurs for a variety of inputs.  Boundaries - explicit and implicit - are often a rich vein to be mined for defects.  Try other kinds of interesting input as well, such as special characters, exceedingly long strings, and improperly-formatted data.  Input that comes from other systems or users will often send strange or incorrect data.  It's good to know what happens when your system receives it."
