### ISSUE TITLE
Can exponents be superscripted instead of using ^?

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#76]
There are a bunch of places that you're expressing exponents as something like "10^80", and that's exactly how they come out in the PDF... is there a way to express those so they're rendered as exponents instead? Not a huge deal, but figured it would look nicer.

**Comment by timparenti** [comment]
IIRC, `pandoc` will pass TeX-ified math on to `pdflatex`, so entering math mode should work, e.g.:

```latex
$10^80$
```

Downside is that wouldn't render in the Markdown.

I can offer to make a pass-through for math typesetting of this nature if @laboon thinks this is worthwhile.

**Comment by laboon** [comment]
I know it's suboptimal in the finished product, but I like the fact that it's visible and understandable right now in all formats (raw, markdown, PDF).  I think I'm going to keep it in the x ^ y format for now.  Maybe I've been programming too long but that actually looks more understandable to me (since ^ is just another operator...)
